### ISSUE TITLE
If there is other iphone models Planned?

### ISSUE THREAD

**Issue by xAstroBoy** [kenp-io/not-for-iphone-usb-c#2]
I have a  11 Pro max, i would love to apply this mod, so i can stop using apple's lighting port cables and use a normal usb-c cable.

**Comment by 00ihsan** [comment]
I want for ip-13-pro

**Comment by ManiPaul83** [comment]
This is the FUNNIEST THING in the world I actually did this to my wife's IPhone 12 Pro like almost 1 year ago. Do people actually want to buy these things?

**Comment by KnechtNoobrecht** [comment]
> 
> 
> This is the FUNNIEST THING in the world I actually did this to my wife's IPhone 12 Pro like almost 1 year ago. Do people actually want to buy these things?

Proof or it didn't happen.

**Comment by 555wolfman** [comment]
When someone spends >100 hours in doing something like that he/she should either invest another 2 hours to document and opensource it or make a product or service out of it to earn money. Kenp went route #1.  What did you do @ManiPaul83 ?

**Comment by 555wolfman** [comment]
@kenp-io when someone sponsors you 2-3 iPhone 13 or 13 pro as a working material for development / testing / trashing would you consider adapting and blueprinting it?
I am sure a company in far east would “help” users to mass-produce and sell the components via aliexpress. From there everyone could buy them and give it to the local smartphone repair shop for installing it. 
watching the auction of your iPhone X i think there is enough demand for it. And maybe once there are 100k modded phones apple would consider implementing it in future phones. Properbly only for expensive models or as $100 upgrade option.

**Comment by OmgImAlexis** [comment]
@555wolfman they're moving to USB-C at some point. It's inevitable.

**Comment by xAstroBoy** [comment]
> @555wolfman they're moving to USB-C at some point. It's inevitable.

Yeah, but not for older models sadly, hence why the mod.

**Comment by OmgImAlexis** [comment]
> > @555wolfman they're moving to USB-C at some point. It's inevitable.
> 
> Yeah, but not for older models sadly, hence why the mod.

I'm talking about this line specifically "And maybe once there are 100k modded phones apple would consider implementing it in future phones.". Apple will be switching to usb-c at some point. Having modded phones has nothing todo with that.

**Comment by xAstroBoy** [comment]
> > > @555wolfman they're moving to USB-C at some point. It's inevitable.
> > 
> > 
> > Yeah, but not for older models sadly, hence why the mod.
> 
> I'm talking about this line specifically "And maybe once there are 100k modded phones apple would consider implementing it in future phones.". Apple will be switching to usb-c at some point. Having modded phones has nothing todo with that.

By the EU laws apple with the newest models will be forced to switch to USB - C , maybe we can mod and move these component to the older phones?

**Comment by kenp-io** [comment]
There's a lot of eyes on this repo now. Surely some people will tackle a port to other models. 

I might do another port myself (probably iPhone 12 or 12 Pro) because I plan to do other mods, and it would be cool to add USB-C while I'm at it.

I wouldn't be surprised if we see some conversion kits pop up on AliExpress in a few weeks. That would be funny.

The EU law has not been passed yet. When it does, manufacturers will have two years to make the switch. We're not there yet, and I would say the iPhone switching to fully wireless is more likely.
