### ISSUE TITLE
iOS updates

### ISSUE THREAD

**Issue by jsonzm** [kenp-io/not-for-iphone-usb-c#6]
What are the chances that an update would break the port? Seems like the OS would still think it’s Lighting.. that is even if it could communicate or detect the chip?

**Comment by fischer-felix** [comment]
To the phone it should look like a lightning to c cable, so it is very unlikely, but it's apple, so you never know.

**Comment by kenp-io** [comment]
Chances are here but low. It could break after an update because the authentication chip is not original. You see this sometimes with those fake cables, they get 'banned' on newer versions of iOS.
