### ISSUE TITLE
Idea: Same mod possible on apple accessories? Mac Magic Keyboard and Mouse? AirPods?

### ISSUE THREAD

**Issue by aescolastico** [kenp-io/not-for-iphone-usb-c#7]
Do you think this same mod could be feasible on those other accessories? I imagine the Mac peripherals would have less of space constraint inside their respective housings. But would the same approach to the electronics work?

**Comment by ghost** [comment]
Personally the issue is opening the devices such as the magic keyboard and trackpad, it’s practically impossible to do so without ruining them permanently

**Comment by kenp-io** [comment]
Yes the same approach would work on all Apple products with a Lightning port. They challenge is to get them open as @KardCreator mentioned ;)
