### ISSUE TITLE
CF205C1-V3 board and YA271D board

### ISSUE THREAD

**Issue by sabogalc** [kenp-io/not-for-iphone-usb-c#8]
Hello, I apologize if opening an issue was the wrong way to share this information, but I wanted to see if any of this information would be helpful.

I am a huge fan of this modification, and I've been wanting to replace the lightning port on my iPhone 6S with USB-C. However, my soldering skills are still pretty elementary, so the way I thought of doing it was by purchasing a USB-C to lightning adapter, and then internalizing it in the phone.

I ended up buying [this 2-pack of adapters from eBay](https://ebay.com/itm/254807452210). The same product seems to be available [on Amazon](https://amazon.com/dp/B09CP6FJR3). The adapter worked with all of the chargers I tried, including high wattage USB-C to USB-C cables. Additionally, it also worked for data connections to my computer (iTunes, checkra1n, 3uTools, etc). I took one of them apart (and broke it in the process), and my photos are attached below.

First, here is an adapter that has been taken apart side-by-side with the adapter that has been left as-is.
![20220419_012758](https://user-images.githubusercontent.com/53708281/163927784-2473cc82-8859-462b-a960-c7ff808a87ee.jpg)
![20220419_012743](https://user-images.githubusercontent.com/53708281/163927782-a8e6c7fa-8d44-4691-8cfc-62e0b482a89b.jpg)

I don't have a high quality camera, so I just did my best with some good lighting and my phone's zoom.
![20220419_013033](https://user-images.githubusercontent.com/53708281/163928095-8d326beb-43cf-4de7-8e22-4b4fd0783637.jpg)
![20220419_013010](https://user-images.githubusercontent.com/53708281/163928084-a04c43fd-a72c-43e3-a139-f28d8be89367.jpg)
The text of the black component on the left clearly reads "AD501". The other component is not as clear, but it looks like it says "3415". With some light internet searching, I found that the 3415 component appears to be a MOSFET ([Possible documentation](https://www.semiee.com/file/backup2/KEXIN-AO3415A.pdf) and [AliExpress listing](https://aliexpress.com/i/33007635827.html)). I was unable to find a 6-pin AD501 component like the one on this board, but I did find an obsolete 5-pin component [from Analog](https://analog.com/en/products/ad501.html#product-overview) and [an AliExpress listing](https://aliexpress.com/item/32533768836.html) for what appears to be the same component.

I'm not sure how to measure the resistors now that my board is broken, but I do believe that the leftmost resistor in the row of three under the MOSFET is the 5.1 kOhm resistor used for USB-C to USB-C functionality since it has a trace to the fifth pin.

I will attempt to contact the seller to see if I can purchase the board on its own (I couldn't find anything on the internet matching CF205C1 or CF205C1-V3). Please let me know if any of this information was helpful or relevant, as well as if you can help me further understand this board.

**Comment by kenp-io** [comment]
Thanks for all of this.

You'll probably want to purchase a multimeter to measure the values of the resistors (desolder them first) and to create a schematic for this board. 

I doubt you will find a seller for that AD501 chip, usually they are only sold on the blackmarket in China, for obvious reasons. Here AD501 does the authentication with the phone and then I will bet it is connected to the gate of the 3415 MOSFET which will then let current flow to the phone. The way you purchase AD501 is by buying more of those adapters on Amazon. 

Good luck for your project, please do post the results here.

**Comment by sabogalc** [comment]
Hello again, no big findings yet, but [this reddit post](https://redd.it/u8w9ay), made me aware of [another adapter](https://amazon.com/dp/B09V85S3VS) that supports up to 18W and looks easier to take apart than the one I already have.

Unfortunately this adapter is a bit larger, so it will be more difficult to put it inside of the phone, but I'm sure I could just snag the components from it and place it on a different board or flex cable much like you did. I'm looking forward to ordering this adapter and taking it apart, and I will post my findings here when I've done so.

**Comment by sabogalc** [comment]
I have purchased the other adapter, and it is much more complex than the previous one. Unfortunately, this one also stopped working after I finished taking it apart, and it was about the same in terms of difficulty of opening as the other one. I used box cutters, a small flathead screwdriver, and my soldering iron to get into the adapter. I suspect it doesn't work any more because on the side labeled 2142, it appears that I knocked off a component in the top right area while removing the rubbers shielding. I attempted to "fix" this by shorting the pads together and seeing if anything changed, but this did not help. Below are my photos of both sides of the board.
![20220507_172909](https://user-images.githubusercontent.com/53708281/167272456-a27f37cc-2afe-4ccc-ae97-f7efed2d35af.jpg)
![20220507_172922](https://user-images.githubusercontent.com/53708281/167272457-8efa0d26-5d5a-42cd-b06d-9176bd8c600b.jpg)
![20220507_173009](https://user-images.githubusercontent.com/53708281/167272461-7118cfee-2701-4f54-a9e3-416699dc5920.jpg)
![20220507_172932](https://user-images.githubusercontent.com/53708281/167272459-7ff3a66e-3a49-439a-b5a9-27feb76ccfc5.jpg)
![20220507_173034](https://user-images.githubusercontent.com/53708281/167272463-06658b4f-8544-401e-a640-568eee1f5778.jpg)
![20220507_173047](https://user-images.githubusercontent.com/53708281/167272454-89103339-567e-432f-baf2-c2c59e1a674a.jpg)
In the last set of photos, I tried to make the writing on the chips as visible as possible, but the only component I was able to find anything for was the one labeled G7P03, which appears to be a MOSFET (data sheet [here](https://datasheet.lcsc.com/lcsc/2009211935_GOFORD-G7P03L_C840062.pdf)).

The first adapter seems to be a better candidate for reverse engineering than this one given its simpler design and smaller number of components, but I'm still quite rusty with KiCad, and I don't quite know how to measure SMD resistors and capacitors with a multimeter (they seem to read 0 when they're just loose/on their own, and I don't know what I'm doing wrong).

If there is anyone who knows more than me that would like me to ship these PCBs to them for further research, I would gladly do so.

**Comment by sabogalc** [comment]
Sorry for going so long without an update. I had a lot of practicing to do and equipment to purchase.

I have purchased a high quality microscope camera, so I was able to get more detailed shots of the PCBs. Below, I have attached shots of both PCBs, front and back, with both the components populated and removed so that the traces are visible.

![Second Lightning USB-C Front](https://user-images.githubusercontent.com/53708281/206851782-89b958e3-0ad5-4212-beaa-a6a699e95bef.jpg)
![Second Lightning USB-C Back](https://user-images.githubusercontent.com/53708281/206851788-49bb5c92-d411-40b0-ae0b-1da98c444d32.jpg)
![Empty Second Lightning USB-C Front](https://user-images.githubusercontent.com/53708281/206851790-6532b479-7cac-4531-b720-c40c64749587.jpg)
![Lightning USB-C Front](https://user-images.githubusercontent.com/53708281/206851794-d46eb167-65d0-4459-a6ac-3b2ed44facfd.jpg)
![Lightning USB-C Back](https://user-images.githubusercontent.com/53708281/206851797-6c27901f-2a0b-4401-84d0-081635204556.jpg)
![Empty Lightning USB-C Front](https://user-images.githubusercontent.com/53708281/206851803-a2c00c2e-0985-447f-b8fd-90d868fd19fa.jpg)
![Empty Lightning USB-C Back](https://user-images.githubusercontent.com/53708281/206851808-1b1f1894-7480-4178-bbdd-b8fab32cdd36.jpg)

Unfortunately, my multimeter isn't very good (it is a cheap ~$10 model), so there is not much I can do to test what these components actually measure at. The only two components I could confirm were the two 5.1 kΩ resistors on the board labeled CF205C1-V3. They are the two components immediately to the right of the capacitor in the bottommost row of components.

Please let me know if any additional information or photographs would be useful.

**Comment by sabogalc** [comment]
Ok, I'm coming in with my final update.

So I've figured out how these adapters function. The CF205C1-V3 board is just a USB-A Lightning header with a Type-C port soldered to the end of it. Similar boards can be found at the AliExpress listings below (albeit missing the Type-C connector).
https://www.aliexpress.com/item/3256804860282595.html
https://www.aliexpress.com/item/2251832875691437.html
https://www.aliexpress.com/item/3256804589752442.html
https://www.aliexpress.com/item/3256804257414782.html

These boards feature the same 6-pin fake authenticator chip and have an overall similar layout to the one I posted about. This would explain why the board is limited to 5V. They are presumably most useful to either make your own cables or to accomplish projects such as this one.

The other board that has more complex chips/circuitry and has support for 9V/PD is similar to the boards below and functions by the same principle.
https://www.aliexpress.com/item/3256804589786016.html
https://www.aliexpress.com/item/3256804918604986.html
https://www.aliexpress.com/item/3256801400060889.html

And there is one last 9V/PD compatible board that is quite similar to the one you used in this project.
https://www.aliexpress.com/item/3256803701941688.html

At this point, I have everything I need to tackle this project. I have also started learning some basic PCB-making skills as I am entering my final year of undergraduate studies for electrical engineering, so I should be able to accomplish this project similarly to you (using the adapter as-is did not prove to be successful for me on my iPhone 6S). I do not feel comfortable enough in my skillset to completely reverse engineer the board and create a flex PCB, but I should be able to fit the fake C94 board in the phone and connect it to a custom USB-C breakout board, similar to the mod in this video - https://youtu.be/1yudWXta6dM. I'll probably use an FFC like [this one](https://www.ebay.com/itm/325017847758) and a PCB custom-fitted to the iPhone 6S (I'll use a set of calipers that I have).

For now I will be closing the ticket since I believe I have all the information I need to perform this mod, but if I am successful I will post about it here.

P.S. are the PCB files going to be added to this repository?
